name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  formatting:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'sbt'
        cache-dependency-path: | # optional
          build.sbt
    - uses: sbt/setup-sbt@v1
    - name: Formatting
      shell: bash
      run: sbt scalafmtCheckAll

  build:

    runs-on: ubuntu-22.04
    needs: formatting

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'sbt'
        cache-dependency-path: | # optional
          build.sbt
    - uses: sbt/setup-sbt@v1
    - name: Build and test
      shell: bash
      run: sbt -v +test
